### ISSUE TITLE
Tạo dữ liệu master

### ISSUE THREAD

**Issue by halab4dev** [toiviet/Toi-Viet-Project-Management#2]
Tạo dữ liệu master về các đề thể loại và đề tài của các bài viết

**Comment by halab4dev** [comment]
Hiện tại a đang gộp cả thể loại và đề tài vào làm 1, gọi tạm là ```category```, đang gom được đống sau:

* Thơ
* Truyện ngắn
* Tiểu thuyết
* Sử thi
* Ngụ ngôn
* Cổ tích
* Thần thoại
* Lịch sử - dã sử
* Kiếm hiệp
* Quân sự
* Hồi ký
* Hài hước
* Lãng mạn
* Thiếu nhi
* Đời sống - Xã hội
* Viễn tưởng - giả tưởng
* Bút ký - phóng sự
* Trinh thám - hình sự

Bọn em xem còn nghĩ ra cái gì, bổ sung hộ a :cry:

**Comment by tunanguyen** [comment]
Em nghĩ về cơ bản là đủ anh ạ. Mình thử chia thể loại ra xem.
